trigger:
  branches:
    include:
    - main
    - develop
  paths:
    exclude:
    - README.md

pool: 'agent-01'

variables:
- group : devops-cicd-pipeline
- name: tag
  value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push to ACR
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(IMAGE_REPO_NAME)
        dockerfile: $(System.DefaultWorkingDirectory)/$(DOCKERFILE_PATH)
        containerRegistry: $(ACR_SERVICE_CONNECTION)
        tags: |
          $(tag)
          latest

- stage: DeployDev
  displayName: Deploy to Development
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS Development using Helm
    environment: 'nonprod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: HelmDeploy@0
            displayName: 'Helm Deploy to Development'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: $(K8S_SERVICE_CONN_NONPROD)
              namespace: $(K8S_NS_DEV)
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(System.DefaultWorkingDirectory)/helm'
              releaseName: '$(HELM_RELEASE_NAME)-dev'
              install: true
              waitForExecution: true
              arguments: '--timeout 300s'
              overrideValues: |
                image.repository=$(ACR_SERVER)/$(IMAGE_REPO_NAME)
                image.tag=$(tag)
                environment=development
                replicaCount=1
