apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fe-cms.fullname" . }}
  labels:
    {{- include "fe-cms.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  VITE_API_BASE_URL: "be-cms-dev:3001"